!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! CTEMsoft:  GPL.f90                                                            !
! Copyright (c) 2001, 2002  Marc De Graef/Carnegie Mellon University (CMU)      !
!                                                                               !
!     This program is free software; you can redistribute it and/or modify      !
!     it under the terms of the GNU General Public License as published by      !
!     the Free Software Foundation; either version 2 of the License, or         !
!     (at your option) any later version.                                       !
!                                                                               !
!     This program is distributed in the hope that it will be useful,           !
!     but WITHOUT ANY WARRANTY; without even the implied warranty of            !
!     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             !
!     GNU General Public License for more details.                              !
!                                                                               !
!     You should have received a copy of the GNU General Public License         !
!     along with this program; if not, write to the Free Software               !
!     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA !
!                                                                               !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
program GPL

! This program simply spits out the Gnu General Public License

  write (*,"(A)") '              GNU GENERAL PUBLIC LICENSE'
  write (*,"(A)") '                 Version 2, June 1991'
  write (*,"(A)") ''
  write (*,"(A)") ' Copyright (C) 1989, 1991 Free Software Foundation, Inc.'
  write (*,"(A)") '                          59 Temple Place, Suite 330, '
  write (*,"(A)") '                          Boston, MA  02111-1307  USA'
  write (*,"(A)") ' Everyone is permitted to copy and distribute verbatim copies'
  write (*,"(A)") ' of this license document, but changing it is not allowed.'
  write (*,"(A)") ''
  write (*,"(A)") ''
  write (*,"(A)") '                   GNU GENERAL PUBLIC LICENSE'
  write (*,"(A)") '   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION'
  write (*,"(A)") ''
  write (*,"(A)") '  0. This License applies to any program or other work which contains'
  write (*,"(A)") 'a notice placed by the copyright holder saying it may be distributed'
  write (*,"(A)") 'under the terms of this General Public License.  The "Program", below,'
  write (*,"(A)") 'refers to any such program or work, and a "work based on the Program"'
  write (*,"(A)") 'means either the Program or any derivative work under copyright law:'
  write (*,"(A)") 'that is to say, a work containing the Program or a portion of it,'
  write (*,"(A)") 'either verbatim or with modifications and/or translated into another'
  write (*,"(A)") 'language.  (Hereinafter, translation is included without limitation in'
  write (*,"(A)") 'the term "modification".)  Each licensee is addressed as "you".'
  write (*,"(A)") ''
  write (*,"(A)") 'Activities other than copying, distribution and modification are not'
  write (*,"(A)") 'covered by this License; they are outside its scope.  The act of'
  write (*,"(A)") 'running the Program is not restricted, and the output from the Program'
  write (*,"(A)") 'is covered only if its contents constitute a work based on the'
  write (*,"(A)") 'Program (independent of having been made by running the Program).'
  write (*,"(A)") 'Whether that is true depends on what the Program does.'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 

  write (*,"(A)") ''
  write (*,"(A)") '  1. You may copy and distribute verbatim copies of the Program''s'
  write (*,"(A)") 'source code as you receive it, in any medium, provided that you'
  write (*,"(A)") 'conspicuously and appropriately publish on each copy an appropriate'
  write (*,"(A)") 'copyright notice and disclaimer of warranty; keep intact all the'
  write (*,"(A)") 'notices that refer to this License and to the absence of any warranty;'
  write (*,"(A)") 'and give any other recipients of the Program a copy of this License'
  write (*,"(A)") 'along with the Program.'
  write (*,"(A)") ''
  write (*,"(A)") 'You may charge a fee for the physical act of transferring a copy, and'
  write (*,"(A)") 'you may at your option offer warranty protection in exchange for a fee.'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 

  write (*,"(A)") ''
  write (*,"(A)") '  2. You may modify your copy or copies of the Program or any portion'
  write (*,"(A)") 'of it, thus forming a work based on the Program, and copy and'
  write (*,"(A)") 'distribute such modifications or work under the terms of Section 1'
  write (*,"(A)") 'above, provided that you also meet all of these conditions:'
  write (*,"(A)") ''
  write (*,"(A)") '    a) You must cause the modified files to carry prominent notices'
  write (*,"(A)") '    stating that you changed the files and the date of any change.'
  write (*,"(A)") ''
  write (*,"(A)") '    b) You must cause any work that you distribute or publish, that in'
  write (*,"(A)") '    whole or in part contains or is derived from the Program or any'
  write (*,"(A)") '    part thereof, to be licensed as a whole at no charge to all third'
  write (*,"(A)") '    parties under the terms of this License.'
  write (*,"(A)") ''
  write (*,"(A)") '    c) If the modified program normally reads commands interactively'
  write (*,"(A)") '    when run, you must cause it, when started running for such'
  write (*,"(A)") '    interactive use in the most ordinary way, to print or display an'
  write (*,"(A)") '    announcement including an appropriate copyright notice and a'
  write (*,"(A)") '    notice that there is no warranty (or else, saying that you provide'
  write (*,"(A)") '    a warranty) and that users may redistribute the program under'
  write (*,"(A)") '    these conditions, and telling the user how to view a copy of this'
  write (*,"(A)") '    License.  (Exception: if the Program itself is interactive but'
  write (*,"(A)") '    does not normally print such an announcement, your work based on'
  write (*,"(A)") '    the Program is not required to print an announcement.)'
  write (*,"(A)") ''
  write (*,"(A)") 'These requirements apply to the modified work as a whole.  If'
  write (*,"(A)") 'identifiable sections of that work are not derived from the Program,'
  write (*,"(A)") 'and can be reasonably considered independent and separate works in'
  write (*,"(A)") 'themselves, then this License, and its terms, do not apply to those'
  write (*,"(A)") 'sections when you distribute them as separate works.  But when you'
  write (*,"(A)") 'distribute the same sections as part of a whole which is a work based'
  write (*,"(A)") 'on the Program, the distribution of the whole must be on the terms of'
  write (*,"(A)") 'this License, whose permissions for other licensees extend to the'
  write (*,"(A)") 'entire whole, and thus to each and every part regardless of who wrote it.'
  write (*,"(A)") ''
  write (*,"(A)") 'Thus, it is not the intent of this section to claim rights or contest'
  write (*,"(A)") 'your rights to work written entirely by you; rather, the intent is to'
  write (*,"(A)") 'exercise the right to control the distribution of derivative or'
  write (*,"(A)") 'collective works based on the Program.'
  write (*,"(A)") ''
  write (*,"(A)") 'In addition, mere aggregation of another work not based on the Program'
  write (*,"(A)") 'with the Program (or with a work based on the Program) on a volume of'
  write (*,"(A)") 'a storage or distribution medium does not bring the other work under'
  write (*,"(A)") 'the scope of this License.'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 

  write (*,"(A)") ''
  write (*,"(A)") '  3. You may copy and distribute the Program (or a work based on it,'
  write (*,"(A)") 'under Section 2) in object code or executable form under the terms of'
  write (*,"(A)") 'Sections 1 and 2 above provided that you also do one of the following:'
  write (*,"(A)") ''
  write (*,"(A)") '    a) Accompany it with the complete corresponding machine-readable'
  write (*,"(A)") '    source code, which must be distributed under the terms of Sections'
  write (*,"(A)") '    1 and 2 above on a medium customarily used for software interchange; or,'
  write (*,"(A)") ''
  write (*,"(A)") '    b) Accompany it with a written offer, valid for at least three'
  write (*,"(A)") '    years, to give any third party, for a charge no more than your'
  write (*,"(A)") '    cost of physically performing source distribution, a complete'
  write (*,"(A)") '    machine-readable copy of the corresponding source code, to be'
  write (*,"(A)") '    distributed under the terms of Sections 1 and 2 above on a medium'
  write (*,"(A)") '    customarily used for software interchange; or,'
  write (*,"(A)") ''
  write (*,"(A)") '    c) Accompany it with the information you received as to the offer'
  write (*,"(A)") '    to distribute corresponding source code.  (This alternative is'
  write (*,"(A)") '    allowed only for noncommercial distribution and only if you'
  write (*,"(A)") '   received the program in object code or executable form with such'
  write (*,"(A)") '   an offer, in accord with Subsection b above.)'
  write (*,"(A)") ''
  write (*,"(A)") 'The source code for a work means the preferred form of the work for'
  write (*,"(A)") 'making modifications to it.  For an executable work, complete source'
  write (*,"(A)") 'code means all the source code for all modules it contains, plus any'
  write (*,"(A)") 'associated interface definition files, plus the scripts used to'
  write (*,"(A)") 'control compilation and installation of the executable.  However, as a'
  write (*,"(A)") 'special exception, the source code distributed need not include'
  write (*,"(A)") 'anything that is normally distributed (in either source or binary'
  write (*,"(A)") 'form) with the major components (compiler, kernel, and so on) of the'
  write (*,"(A)") 'operating system on which the executable runs, unless that component'
  write (*,"(A)") 'itself accompanies the executable.'
  write (*,"(A)") ''
  write (*,"(A)") 'If distribution of executable or object code is made by offering'
  write (*,"(A)") 'access to copy from a designated place, then offering equivalent'
  write (*,"(A)") 'access to copy the source code from the same place counts as'
  write (*,"(A)") 'distribution of the source code, even though third parties are not'
  write (*,"(A)") 'compelled to copy the source along with the object code.'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 

  write (*,"(A)") ''
  write (*,"(A)") '  4. You may not copy, modify, sublicense, or distribute the Program'
  write (*,"(A)") 'except as expressly provided under this License.  Any attempt'
  write (*,"(A)") 'otherwise to copy, modify, sublicense or distribute the Program is'
  write (*,"(A)") 'void, and will automatically terminate your rights under this License.'
  write (*,"(A)") 'However, parties who have received copies, or rights, from you under'
  write (*,"(A)") 'this License will not have their licenses terminated so long as such'
  write (*,"(A)") 'parties remain in full compliance.'
  write (*,"(A)") ''
  write (*,"(A)") '  5. You are not required to accept this License, since you have not'
  write (*,"(A)") 'signed it.  However, nothing else grants you permission to modify or'
  write (*,"(A)") 'distribute the Program or its derivative works.  These actions are'
  write (*,"(A)") 'prohibited by law if you do not accept this License.  Therefore, by'
  write (*,"(A)") 'modifying or distributing the Program (or any work based on the'
  write (*,"(A)") 'Program), you indicate your acceptance of this License to do so, and'
  write (*,"(A)") 'all its terms and conditions for copying, distributing or modifying'
  write (*,"(A)") 'the Program or works based on it.'
  write (*,"(A)") ''
  write (*,"(A)") '6. Each time you redistribute the Program (or any work based on the'
  write (*,"(A)") 'Program), the recipient automatically receives a license from the'
  write (*,"(A)") 'original licensor to copy, distribute or modify the Program subject to'
  write (*,"(A)") 'these terms and conditions.  You may not impose any further'
  write (*,"(A)") 'restrictions on the recipients'' exercise of the rights granted herein.'
  write (*,"(A)") 'You are not responsible for enforcing compliance by third parties to'
  write (*,"(A)") 'this License.'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 

  write (*,"(A)") ''
  write (*,"(A)") '  7. If, as a consequence of a court judgment or allegation of patent'
  write (*,"(A)") 'infringement or for any other reason (not limited to patent issues),'
  write (*,"(A)") 'conditions are imposed on you (whether by court order, agreement or'
  write (*,"(A)") 'otherwise) that contradict the conditions of this License, they do not'
  write (*,"(A)") 'excuse you from the conditions of this License.  If you cannot'
  write (*,"(A)") 'distribute so as to satisfy simultaneously your obligations under this'
  write (*,"(A)") 'License and any other pertinent obligations, then as a consequence you'
  write (*,"(A)") 'may not distribute the Program at all.  For example, if a patent'
  write (*,"(A)") 'license would not permit royalty-free redistribution of the Program by'
  write (*,"(A)") 'all those who receive copies directly or indirectly through you, then'
  write (*,"(A)") 'the only way you could satisfy both it and this License would be to'
  write (*,"(A)") 'refrain entirely from distribution of the Program.'
  write (*,"(A)") ''
  write (*,"(A)") 'If any portion of this section is held invalid or unenforceable under'
  write (*,"(A)") 'any particular circumstance, the balance of the section is intended to'
  write (*,"(A)") 'apply and the section as a whole is intended to apply in other'
  write (*,"(A)") 'circumstances.'
  write (*,"(A)") ''
  write (*,"(A)") 'It is not the purpose of this section to induce you to infringe any'
  write (*,"(A)") 'patents or other property right claims or to contest validity of any'
  write (*,"(A)") 'such claims; this section has the sole purpose of protecting the'
  write (*,"(A)") 'integrity of the free software distribution system, which is'
  write (*,"(A)") 'implemented by public license practices.  Many people have made'
  write (*,"(A)") 'generous contributions to the wide range of software distributed'
  write (*,"(A)") 'through that system in reliance on consistent application of that'
  write (*,"(A)") 'system; it is up to the author/donor to decide if he or she is willing'
  write (*,"(A)") 'to distribute software through any other system and a licensee cannot'
  write (*,"(A)") 'impose that choice.'
  write (*,"(A)") ''
  write (*,"(A)") 'This section is intended to make thoroughly clear what is believed to'
  write (*,"(A)") 'be a consequence of the rest of this License.'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 

  write (*,"(A)") ''
  write (*,"(A)") '  8. If the distribution and/or use of the Program is restricted in'
  write (*,"(A)") 'certain countries either by patents or by copyrighted interfaces, the'
  write (*,"(A)") 'original copyright holder who places the Program under this License'
  write (*,"(A)") 'may add an explicit geographical distribution limitation excluding'
  write (*,"(A)") 'those countries, so that distribution is permitted only in or among'
  write (*,"(A)") 'countries not thus excluded.  In such case, this License incorporates'
  write (*,"(A)") 'the limitation as if written in the body of this License.'
  write (*,"(A)") ''
  write (*,"(A)") '9. The Free Software Foundation may publish revised and/or new versions'
  write (*,"(A)") 'of the General Public License from time to time.  Such new versions will'
  write (*,"(A)") 'be similar in spirit to the present version, but may differ in detail to'
  write (*,"(A)") 'address new problems or concerns.'
  write (*,"(A)") ''
  write (*,"(A)") 'Each version is given a distinguishing version number.  If the Program'
  write (*,"(A)") 'specifies a version number of this License which applies to it and "any'
  write (*,"(A)") 'later version", you have the option of following the terms and conditions'
  write (*,"(A)") 'either of that version or of any later version published by the Free'
  write (*,"(A)") 'Software Foundation.  If the Program does not specify a version number of'
  write (*,"(A)") 'this License, you may choose any version ever published by the Free Software'
  write (*,"(A)") 'Foundation.'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 

  write (*,"(A)") ''
  write (*,"(A)") '  10. If you wish to incorporate parts of the Program into other free'
  write (*,"(A)") 'programs whose distribution conditions are different, write to the author'
  write (*,"(A)") 'to ask for permission.  For software which is copyrighted by the Free'
  write (*,"(A)") 'Software Foundation, write to the Free Software Foundation; we sometimes'
  write (*,"(A)") 'make exceptions for this.  Our decision will be guided by the two goals'
  write (*,"(A)") 'of preserving the free status of all derivatives of our free software and'
  write (*,"(A)") 'of promoting the sharing and reuse of software generally.'
  write (*,"(A)") ''
  write (*,"(A)") '			    NO WARRANTY'
  write (*,"(A)") ''
  write (*,"(A)") '  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY'
  write (*,"(A)") 'FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN'
  write (*,"(A)") 'OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES'
  write (*,"(A)") 'PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED'
  write (*,"(A)") 'OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF'
  write (*,"(A)") 'MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS'
  write (*,"(A)") 'TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE'
  write (*,"(A)") 'PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,'
  write (*,"(A)") 'REPAIR OR CORRECTION.'
  write (*,"(A)") ''
  write (*,"(A)") '  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING'
  write (*,"(A)") 'WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR'
  write (*,"(A)") 'REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,'
  write (*,"(A)") 'INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING'
  write (*,"(A)") 'OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED'
  write (*,"(A)") 'TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY'
  write (*,"(A)") 'YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER'
  write (*,"(A)") 'PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE'
  write (*,"(A)") 'POSSIBILITY OF SUCH DAMAGES.'
  write (*,"(A)") ''
  write (*,"(A)") '		     END OF TERMS AND CONDITIONS'
  write (*,"(A)") ''
  read (*,"('Press enter to continue ')") 
end program

